[tool.poetry]
name = "supertrainer2k"
version = "0.1.0"
description = ""
authors = ["Jade <jpritsk@purdue.edu>"]
license = "0BSD"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
transformers = "^4.36.2"
datasets = "^2.16.1"
lightning = "^2.1.3"
pydantic = "^2.5.3"
